php:
  image: quay.io/optionlift/server:latest
  tty: true
  stdin_open: true
  volumes_from:
    - app
  labels:
    io.rancher.sidekicks: app
  external_links:
    - ${RABBIT_HOST}:rabbit
    - ${HEAVEN11_SERVER}:server
  environment:
    RABBIT_PORT: ${RABBIT_PORT}
    RABBIT_USER: ${RABBIT_USER}
    RABBIT_PASSWORD: ${RABBBIT_PASSWORD}

nginx:
  image: quay.io/optionlift/nginx:latest
  tty: true
  stdin_open: true
  labels:
    io.rancher.sidekicks: app, php
  volumes_from:
    - app
  links:
    - php

app:
  image: quay.io/optionlift/client:latest
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: 'true'