version: "3.3"
services:
  php:
    container_name: quay.io/optionlift/php
    build: ./docker/php/
    tty: true
    stdin_open: true
    volumes:
      - app:/opt/app
    networks:
       - overlay
    depends_on:
      - php
      - app

  nginx:
    image: quay.io/optionlift/nginx
    tty: true
    stdin_open: true
    ports:
      - "80:80"
    volumes:
      - app:/opt/app
    depends_on:
      - php
      - app
    networks:
       - overlay

  app:
    image: quay.io/optionlift/client
    networks: none
