server-php:
  image: quay.io/optionlift/php:latest
  tty: true
  stdin_open: true
  volumes_from:
    - server
  links:
    - server
  external_links:
    - ${RABBIT_HOST}:rabbit
  environment:
    RABBIT_PORT: ${RABBIT_PORT}
    RABBIT_USER: ${RABBIT_USER}
    RABBIT_PASSWORD: ${RABBBIT_PASSWORD}
server-nginx:
  image: quay.io/optionlift/nginx
  tty: true
  stdin_open: true
  volumes_from:
    - app
  links:
    - server-php
    - server

server:
  image: quay.io/optionlift/server:latest
  labels:
    io.rancher.container.pull_image: always
    io.rancher.sidekicks: php, nginx
    io.rancher.container.start_once: 'true'