php:
  image: quay.io/optionlift/php:latest
  tty: true
  stdin_open: true
  volumes_from:
    - app
  links:
    - app
  external_links:
    - ${RABBIT_HOST}:rabbit
  environment:
    RABBIT_PORT: ${RABBIT_PORT}
    RABBIT_USER: ${RABBIT_USER}
    RABBIT_PASSWORD: ${RABBBIT_PASSWORD}
nginx:
  image: quay.io/optionlift/nginx
  tty: true
  stdin_open: true
  volumes_from:
    - app
  links:
    - php
    - app

app:
  image: quay.io/optionlift/server:latest
  labels:
    io.rancher.container.pull_image: always