server-php:
  image: quay.io/optionlift/php:latest
  tty: true
  stdin_open: true
  volumes_from:
    - heaven-server
  external_links:
    - ${RABBIT_HOST}:rabbit
  environment:
    RABBIT_PORT: ${RABBIT_PORT}
    RABBIT_USER: ${RABBIT_USER}
    RABBIT_PASSWORD: ${RABBBIT_PASSWORD}
  labels:
    io.rancher.sidekicks: heaven-server
server-nginx:
  image: quay.io/optionlift/nginx
  tty: true
  stdin_open: true
  volumes_from:
    - heaven-server
  links:
    - server-php
  labels:
    io.rancher.sidekicks: server-php, heaven-php

heaven-server:
  image: quay.io/optionlift/server:latest
